name: TenLives
version: '${project.version}'
main: com.gguppy.tenlives.TenLives
api-version: 1.17
authors: [ GGuppy ]
description: Made for zeanna#6073
commands:
    setlives:
        description: Changes a player's lives count and health to match.
        usage: /<command> player amount
